### tempoCidade - Curitiba
GET http://localhost:3000/tempo/Curitiba
Content-Type: application/json

### tempoCidade - SP
GET http://localhost:3000/tempo/Sao Paulo
Content-Type: application/json

### tempoErro - Cidade não encontrada
GET http://localhost:3000/tempo/CidadeNaoExiste123456789
Content-Type: application/json