### tempoCidade - 1
GET http://localhost:3000/tempo/Curitiba
Content-Type: application/json

### tempoCidade - 2
GET http://localhost:3000/tempo/Sao Paulo
Content-Type: application/json

### tempoErro
GET http://localhost:3000/tempo/asd
Content-Type: application/json